# Generated by Django 4.1.7 on 2023-03-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total Amount')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(max_length=250, verbose_name='Payment Intent ID')),
                ('checkout_id', models.CharField(max_length=250, verbose_name='Checkout Id')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('course', models.ManyToManyField(to='courses.course', verbose_name='Courses')),
            ],
        ),
    ]
