# Generated by Django 4.1.7 on 2023-03-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='courses.comment', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_section',
            field=models.ManyToManyField(blank=True, null=True, to='courses.coursesection', verbose_name='Course Section'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='episodes',
            field=models.ManyToManyField(blank=True, null=True, to='courses.episode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='releted_course',
            field=models.ManyToManyField(blank=True, null=True, to='courses.course', verbose_name='Releted Courses'),
        ),
    ]
